name: Build Mod Menu
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # دابەزاندنا SDK ب ڕێکا Git دا تووشی ئەرۆرا Unrecognized archive نەبی
          git clone https://github.com/theos/sdks.git ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build
        run: |
          export THEOS=~/theos
          cd template && make package FINALPACKAGE=1
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Yusuf-Mod-Menu-File
          path: template/packages/*.deb
